sudo: false
language: cpp
compiler:
  - gcc
  - clang

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:  
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  - sudo apt-get update -qq

install:
  - sudo apt-get install --allow-unauthenticated -qq clang++-4.0
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-4"; fi

before_script:  
  - mkdir build
  - cd build
  - cmake -DSF2_BUILD_TESTS=ON ..

script: make all test
