language: cpp

compiler:  
    - gcc
    - clang

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # g++5.2
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5.2; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.2"; fi

  # clang 3.7
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.7; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi

before_script:  
    - mkdir build
    - cd build
    - cmake -DSF2_BUILD_TESTS=ON ..

script: make 
